backend:
  name: git-gateway
  repo: dumjeeckham-oss/dong100-home
  branch: main
  auth_endpoint: api/github-proxy

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
